### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by kapil-rss** [Kommunicate-io/Kommunicate-Web-SDK#521] opened 2020-07-31 05:42 UTC
bundle.min.js.map
tiny-slider.css.map

**Comment by ab14bhardwaj** [comment] 2020-07-31 07:36
@kapil-rss We're not generating any bundle.min.js file in our codebase.
This might not be from our side.
You can safely ignore the warning given for tiny-slider.css.map.

If you're facing further issues, please help us with more information on how to get this issue?
Steps to reproduce this issue will be plus.

Thanks

**Comment by kapil-rss** [comment] 2020-07-31 08:02
Thanks Without these two files. Node app doesnt start

Regards
Kapil
02031987365
________________________________

**Comment by ab14bhardwaj** [comment] 2020-08-11 18:03
Hello @kapil-rss 
You can use the production environment command to run the node app, it won't happen.
>$ NODE_ENV=prod node app

We will remove the source map path lines from the minified files of tiny-slider in our next release.
You can pull the recent changes by the end of this week.

Thanks.

**Comment by kapil-rss** [comment] 2020-08-11 18:31
Thanks again. We will wait for the release.


Regards
Kapil
02031987365
________________________________

**Comment by ab14bhardwaj** [comment] 2020-08-13 21:49
@kapil-rss 
We have released the changes, you can pull the recent changes from the master branch.

I hope your issue is fixed now.

**Comment by ab14bhardwaj** [comment] 2020-08-23 21:23
@kapil-rss Since there was no response, we're closing this issue.
Please reopen in case the issue persists.

**Closed by ab14bhardwaj** 2020-08-23 21:23 UTC
