### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by kapil-rss** [Kommunicate-io/Kommunicate-Web-SDK#520] opened 2020-07-31 05:42 UTC
How can we configure SSL?

**Comment by ab14bhardwaj** [comment] 2020-08-11 18:04
@kapil-rss 
That will be done from your end, you can consult your dev-ops team regarding the same.

**Comment by kapil-rss** [comment] 2020-08-11 18:31
Thanks Abhinav. We have made the required changes.


Regards
Kapil
02031987365
________________________________

**Comment by ab14bhardwaj** [comment] 2020-08-11 18:51
The issue is resolved.
Closing this issue.

**Closed by ab14bhardwaj** 2020-08-11 18:52 UTC
